services:
  - type: web
    name: fullstack-app
    runtime: python
    buildCommand: |
      # Backend setup
      cd backend && 
      pip install -r requirements.txt &&
      # Frontend setup
      cd ../frontend &&
      npm install &&
      npm run build
    startCommand: |
      cd backend &&
      gunicorn app:app --bind :$PORT
    staticDir: frontend/build
    envVars:
      - key: FLASK_ENV
        value: production