"""Initial models with users, books, clubs, reviews, discussions, and summaries

Revision ID: 791db1d455a0
Revises: a0038e70a145
Create Date: 2025-05-05 04:17:24.375730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791db1d455a0'
down_revision = 'a0038e70a145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('club_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('discussion_replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('discussion_replies', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('club_members', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('book_clubs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
