"""Initial models with users, books, clubs, reviews, discussions, and summaries

Revision ID: a0038e70a145
Revises: 
Create Date: 2025-05-05 03:55:38.415407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0038e70a145'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.String(length=500), nullable=True))
        batch_op.drop_column('rating_review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_review', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('review')

    # ### end Alembic commands ###
