"""Create Book model

Revision ID: 000d53a88e97
Revises: 7aeb8ee88ca2
Create Date: 2025-04-29 23:57:47.445848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '000d53a88e97'
down_revision = '7aeb8ee88ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('summary')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('genre',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('year')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
