"""Update membership model

Revision ID: 379e8633c7df
Revises: 0cff4f939417
Create Date: 2025-05-07 02:10:00.263621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379e8633c7df'
down_revision = '0cff4f939417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
