"""Removed book_id and adjusted relationships

Revision ID: 4705f2eb1f55
Revises: 9bae16855b37
Create Date: 2025-05-12 17:23:37.273466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4705f2eb1f55'
down_revision = '9bae16855b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_constraint('summaries_book_id_fkey', type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('summaries_book_id_fkey', 'books', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
