"""Add is_active column to users table

Revision ID: 475380d59a72
Revises: 8fa7e7b93526
Create Date: 2025-05-06 01:01:00.834406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475380d59a72'
down_revision = '8fa7e7b93526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
