"""added lastname and firstname

Revision ID: 579076de98e8
Revises: edba1327a9de
Create Date: 2025-05-11 01:19:23.046322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579076de98e8'
down_revision = 'edba1327a9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
