"""ENUM

Revision ID: 6820469f9779
Revises: fc89db871a4a
Create Date: 2025-05-08 12:08:42.962890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6820469f9779'
down_revision = 'fc89db871a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='invitestatus'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', name='invitestatus'),
               nullable=True)

    # ### end Alembic commands ###
