"""update summary table

Revision ID: 71b731b6ea37
Revises: 5e07d678c655
Create Date: 2025-05-04 14:37:15.084916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71b731b6ea37'
down_revision = '5e07d678c655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_club_members')
    op.drop_table('membership')
    #op.drop_table('book_clubs')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('bookclub_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.alter_column('bookclub_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.alter_column('bookclub_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('bookclub_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('book_clubs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('book_clubs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('synopsis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='book_clubs_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='book_clubs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('membership',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bookclub_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bookclub_id'], ['bookclubs.id'], name='membership_bookclub_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='membership_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='membership_pkey')
    )
    op.create_table('book_club_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_club_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_club_id'], ['book_clubs.id'], name='book_club_members_book_club_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='book_club_members_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='book_club_members_pkey')
    )
    # ### end Alembic commands ###
