"""Added current book JSON field to BookClub model

Revision ID: c83ce65f6112
Revises: a1c1dce83aea
Create Date: 2025-05-09 22:16:17.550003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c83ce65f6112'
down_revision = 'a1c1dce83aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_books')
    with op.batch_alter_table('bookclubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_book', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookclubs', schema=None) as batch_op:
        batch_op.drop_column('current_book')

    op.create_table('current_books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bookclub_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='current_books_book_id_fkey'),
    sa.ForeignKeyConstraint(['bookclub_id'], ['bookclubs.id'], name='current_books_bookclub_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='current_books_pkey'),
    sa.UniqueConstraint('bookclub_id', name='current_books_bookclub_id_key')
    )
    # ### end Alembic commands ###
