"""Add synopsis

Revision ID: e94490afcd37
Revises: d99dd097c22a
Create Date: 2025-05-01 23:29:39.245978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94490afcd37'
down_revision = 'd99dd097c22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synopsis', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('synopsis')

    # ### end Alembic commands ###
